(define gui #f)
(define width 402)
(define height 874)
(define padding 20)

(define camera-image (string-append (system-directory) (system-pathseparator) "leaf.jpg"))
(define camera-image2 (string-append (system-directory) (system-pathseparator) "leaf.png"))

(define lastmodtime 0.)

(define vh(lambda(h)
    (set! h (/ h 100))
    (set! h (* h height))
    (+ h 0)
))

(define center(lambda(w)
    (set! w (- width w))
    (set! w (/ w 2))
    (+ w 0)
))

(define result (lambda(t p)
    (glgui-box gui (center (- width padding)) (vh p) (- width padding) (vh 7) Black)
    (glgui-box gui (+ (center (- width padding)) 1) (+ (vh p) 1) (- (- width padding) 2) (- (vh 7) 2) White)
    (glgui-label gui (+ (center (- width padding)) (vh 10)) (vh p) (- width padding) (vh 7) t dejavu_16.fnt Black)
))

(define (autoload)
  (let* ((fileinfo (if (file-exists? camera-image) (file-info camera-image) #f))
         (modtime  (if fileinfo (time->seconds (file-info-last-modification-time fileinfo)) #f)))
    (if (and gui background modtime (> modtime lastmodtime))
        (let* ((gdf (gdFileOpen camera-image "r"))
               (gd  (gdImageCreateFromJpeg gdf))
               (w   (gdImageSX gd))
               (h   (gdImageSY gd))
               (w2  260)
               (h2  260)
               (offset (/ (- h w) 2))
               (gdf2 (gdFileOpen camera-image2 "w"))
               (gd2 (gdImageCreateTrueColor w2 h2)))
         (gdImageCopyResampled gd2 gd 0 0 0 offset w2 h2 w w)
         (gdImagePng gd2 gdf2)
         (gdImageDestroy gd)
         (gdImageDestroy gd2)
         (gdFileClose gdf)
         (gdFileClose gdf2)
         (let ((img (if (file-exists? camera-image2) (png->img camera-image2) #f)))
           (glgui-widget-set! gui img-box 'image img))
         (set! lastmodtime modtime)
      ))))


(main
    (lambda (w h)
        (make-window width height)
        (glgui-orientation-set! GUI_PORTRAIT)

        (set! gui (make-glgui))
        (glgui-box gui 0 0 width height White)
        ;;(glgui-box gui (center 100) (vh 5) 100 100 Green)
        (glgui-button gui (center 100) (vh 5) 100 100 default.img (lambda (un . used) 
            (camera-start camera-image)
        ))
        (result " Leaf Mold (98%)" 40)
        (result " Bacterial Spot (73%)" 30)
        (result " Early Blight (54%)" 20)
        (glgui-label gui (center (- width 20)) (vh 50) width (vh 10) "Results" dejavubold_32.fnt Black)
        (glgui-box gui (center (vh 30)) (vh 65) (vh 30) (vh 30) Black)
        (set! img-box (glgui-image gui (center (vh 30)) (vh 65) (vh 30) (vh 30) splash.img White))
        (if (file-exists? camera-image) (delete-file camera-image))
        (if (file-exists? camera-image2) (delete-file camera-image2))
        (let ((logdir (string-append (system-directory) "/log")))
        (if (not (file-exists? logdir)) (create-directory logdir)))
    )

    (lambda (t x y)
        (autoload)
        (if (= t EVENT_KEYPRESS) (begin
        (if (= x EVENT_KEYESCAPE) (terminate))))
        (glgui-event gui t x y)
    )

    (lambda () #t)

    (lambda () (glgui-suspend))

    (lambda () (glgui-resume))
)