name: debian-build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: debian
    runs-on: ubuntu-latest
    container:
      image: debian:sid

    steps:
    - uses: actions/checkout@v7
    - run: cat /etc/os-release
    - name: install dependencies
      run: |
       apt -y update
       apt -y install android-platform-tools-base android-sdk android-sdk-helper
       apt -y install android-sdk-build-tools android-sdk-platform-tools ant
       apt -y install autoconf automake bc cmake gambc gcc git g++ imagemagick make
       apt -y install libasound2-dev libfindbin-libs-perl libgl1-mesa-dev
       apt -y install libglu1-mesa-dev libgradle-android-plugin-java libnetpbm-dev
       apt -y install libportaudio2 libtool libxext-dev openjdk-17-jdk
       apt -y install sdkmanager tar tcl-dev texlive tree unzip wget zip
    - name: Get LambdaNative
      run: |
       git clone --branch=tinymaix https://github.com/bkmgit/lambdanative.git
    - name: Get fixed commit
      working-directory: lambdanative
      run: |
        git checkout d936db275b8f40c9e1381783df03c8981ecc5481
    - name: setup android
      run: |
       # https://stackoverflow.com/a/77215395
       # https://computingforgeeks.com/install-and-use-android-studio-on-fedora/
       mkdir -p /home/build/android-sdk
       mkdir -p /home/.cache/lambdanative/android/support
       export ANDROID_HOME=/home/build/android-sdk
       echo yes | sdkmanager --sdk_root=/home/build/android-sdk "platforms;android-22"
       echo yes | sdkmanager --sdk_root=/home/build/android-sdk "build-tools;33.0.0"
       echo yes | sdkmanager --sdk_root=/home/build/android-sdk "tools;22.0.1"
       echo yes | sdkmanager --sdk_root=/home/build/android-sdk "extras;android;m2repository;22"
       echo yes | sdkmanager --sdk_root=/home/build/android-sdk "ndk-bundle;r22"
       echo yes | sdkmanager --sdk_root=/home/build/android-sdk "platform-tools;24.0.0"
       echo yes | sdkmanager --sdk_root=/home/build/android-sdk --licenses

       # https://coderwall.com/p/r09hoq/android-generate-release-debug-keystores
       # https://stackoverflow.com/a/13578480
       keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -noprompt -dname "CN=Unknown, OU=Unknown, O=Unknown, L=Unknown, S=Unknown, C=Unknown"
    - name: prepare lambdanative
      working-directory: lambdanative
      run: |
       cp SETUP.template SETUP
       sed -i 's/ANDROIDAPI=21/ANDROIDAPI=22/g' SETUP
       sed -i 's|/usr/local/android-sdk-*|/home/build/android-sdk|g' SETUP
       sed -i 's|/usr/local/android-ndk-*|/home/build/android-sdk/ndk-bundle|g' SETUP
       cp PROFILE.template PROFILE
       sed -i 's|SYS_ANDROIDPW="yoursecrethere"|SYS_ANDROIDPW="android"|g' PROFILE
       sed -i 's|=ranlib|="$(which ranlib)"|g' targets/linux/host_linux
    - name: copy source
      run: |
       cp -r tomato lambdanative/apps
    - name: linux builds
      working-directory: lambdanative
      run: |
       ./configure tomato linux debug
       #./make.sh all
    - name: android builds
      working-directory: lambdanative
      run: |
        # Fedora only provides Python3
        sed -i 's/python/python3/g' targets/android/check-tools
        ./configure tomato android debug
        ./make.sh all
    - uses: actions/upload-artifact@v7.0.1
      with:
       name: apk
       path: /github/home/.cache/lambdanative/packages/*.apk
       archive: false
